[[redirects]]
  from = "/instermat/*"
  to = "https://my.insterburg.org/rental-status"
  status = 302
  force = true
  
[[redirects]]
  from = "/vote/*"
  to = "https://services.insterburg.org/vote/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "source_key"
    X-Api-Key = "3echjj4rRTpYXrN4ZyaN8V6kF"
    
[[redirects]]
  from = "/door/*"
  to = "https://services.insterburg.org/door/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "source_key"
    X-Api-Key = "3echjj4rRTpYXrN4ZyaN8V6kF"
    
[[redirects]]
  from = "/elevator/*"
  to = "https://services.insterburg.org/elevator/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "source_key"
    X-Api-Key = "3echjj4rRTpYXrN4ZyaN8V6kF"