[[redirects]]
  from = "/instermat/*"
  to = "https://my.insterburg.org/rental-status"
  status = 302
  force = true

[[redirects]]
  from = "/door/*"
  to = "https://my.insterburg.org/door-opener"
  status = 302
  force = true